/*
  # App Data Tables (localStorage -> Supabase migration)

  1. New Tables
    Each business entity from the frontend (previously stored in
    localStorage) gets a "JSONB blob" table:
      - `products`
      - `orders` (+ generated `status` column for realtime/kitchen filters)
      - `customers`
      - `cadetes`
      - `daily_reports`
      - `cash_shifts`
      - `completed_orders`
      - `raw_materials`
      - `stock_movements`
      - `sub_products`
      - `extras`

    All of them share the same shape:
      - `id` (text, primary key) - matches the id already generated by the app
      - `data` (jsonb, not null) - the full object as used by the frontend (camelCase)
      - `updated_at` (timestamptz)

    Additionally:
      - `app_settings`: generic key/value store for app-wide settings
        (currently used for `currentOrderNumber`)
        - `key` (text, primary key)
        - `value` (jsonb, not null)
        - `updated_at` (timestamptz)

  2. Security
    - Enable RLS on all tables
    - Single shared staff account: any authenticated user can manage all rows
      (FOR ALL TO authenticated USING (true) WITH CHECK (true))

  3. Realtime
    - All tables added to the `supabase_realtime` publication so multiple
      devices stay in sync live
*/

-- Products
CREATE TABLE IF NOT EXISTS products (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage products"
  ON products FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Orders (with generated status column for filtering/realtime)
CREATE TABLE IF NOT EXISTS orders (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  status text GENERATED ALWAYS AS (data->>'status') STORED,
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage orders"
  ON orders FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Customers
CREATE TABLE IF NOT EXISTS customers (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage customers"
  ON customers FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Cadetes
CREATE TABLE IF NOT EXISTS cadetes (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE cadetes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage cadetes"
  ON cadetes FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Daily Reports
CREATE TABLE IF NOT EXISTS daily_reports (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE daily_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage daily reports"
  ON daily_reports FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Cash Shifts
CREATE TABLE IF NOT EXISTS cash_shifts (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE cash_shifts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage cash shifts"
  ON cash_shifts FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Completed Orders
CREATE TABLE IF NOT EXISTS completed_orders (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE completed_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage completed orders"
  ON completed_orders FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Raw Materials
CREATE TABLE IF NOT EXISTS raw_materials (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE raw_materials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage raw materials"
  ON raw_materials FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Stock Movements
CREATE TABLE IF NOT EXISTS stock_movements (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage stock movements"
  ON stock_movements FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Sub Products
CREATE TABLE IF NOT EXISTS sub_products (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE sub_products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage sub products"
  ON sub_products FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Extras
CREATE TABLE IF NOT EXISTS extras (
  id text PRIMARY KEY,
  data jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE extras ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage extras"
  ON extras FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- App Settings (key/value store, e.g. currentOrderNumber)
CREATE TABLE IF NOT EXISTS app_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage app settings"
  ON app_settings FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Enable realtime for all tables above (idempotent)
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE products;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE orders;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE customers;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE cadetes;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE daily_reports;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE cash_shifts;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE completed_orders;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE raw_materials;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE stock_movements;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE sub_products;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE extras;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE app_settings;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
